### ISSUE TITLE
Failed to register native method org.chickenhook.restrictionbypass.NativeReflectionBypass.getMethod

### ISSUE THREAD

**Issue by magiclingfeng** [ChickenHook/RestrictionBypass#12]
Here is my config
release {
            // Enables code shrinking, obfuscation, and optimization for only
            // your project's release build type. Make sure to use a build
            // variant with `debuggable false`.
            minifyEnabled true
            // Enables resource shrinking, which is performed by the
            // Android Gradle plugin.
            shrinkResources = true
}

Here is error
2023-07-14 21:20:52.125  1515-1628  VerityUtils             system_server                        E  Failed to measure fs-verity, errno 1: /data/app/~~x5jMNqx-TxiFPoMGtRaQGA==/com.flairtime.Flare-r-QNkCPaVrUPHTLeSKMkpA==/base.apk
2023-07-14 21:20:52.316 16708-16708 flairtime.Flare         pid-16708                            E  Failed to register native method org.chickenhook.restrictionbypass.NativeReflectionBypass.getMethod(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method; in /data/app/~~x5jMNqx-TxiFPoMGtRaQGA==/com.flairtime.Flare-r-QNkCPaVrUPHTLeSKMkpA==/base.apk!classes2.dex
2023-07-14 21:20:52.316 16708-16708 AndroidRuntime          pid-16708                            E  FATAL EXCEPTION: main
                                                                                                    Process: com.flairtime.Flare, PID: 16708
                                                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~x5jMNqx-TxiFPoMGtRaQGA==/com.flairtime.Flare-r-QNkCPaVrUPHTLeSKMkpA==/base.apk!/lib/arm64-v8a/libnrb.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at org.chickenhook.restrictionbypass.NativeReflectionBypass.<clinit>(SourceFile:3)
                                                                                                    	at org.chickenhook.restrictionbypass.a.a(SourceFile:7)
                                                                                                    	at org.chickenhook.restrictionbypass.a.b(SourceFile:12)
                                                                                                    	at org.chickenhook.restrictionbypass.BypassProvider.attachInfo(SourceFile:4)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7474)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6985)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6756)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-07-14 21:20:52.453  1515-1628  VerityUtils             system_server                        E  Failed to measure fs-verity, errno 1: /data/app/~~x5jMNqx-TxiFPoMGtRaQGA==/com.flairtime.Flare-r-QNkCPaVrUPHTLeSKMkpA==/base.apk
2023-07-14 21:20:55.462 16914-16914 flairtime.Flare         com.flairtime.Flare                  E  Not starting debugger since process cannot load the jdwp agent.
2023-07-14 21:20:55.639 16914-16914 flairtime.Flare         com.flairtime.Flare                  E  ----- class 'Lorg/chickenhook/restrictionbypass/NativeReflectionBypass;' cl=0x12c27f20 -----
                                                                                                      objectSize=120 (224 from super)
                                                                                                      access=0x0000.0400
                                                                                                      super='java.lang.Class<java.lang.Object>' (cl=0x0)
                                                                                                      vtable (0 entries, 11 in super):
                                                                                                      direct methods (2 entries):
                                                                                                         0: void org.chickenhook.restrictionbypass.NativeReflectionBypass.<clinit>()
                                                                                                         1: java.lang.reflect.Method org.chickenhook.restrictionbypass.NativeReflectionBypass.getDeclaredMethod(java.lang.Object, java.lang.String, java.lang.Class[])
2023-07-14 21:20:55.639 16914-16914 flairtime.Flare         com.flairtime.Flare                  E  Failed to register native method org.chickenhook.restrictionbypass.NativeReflectionBypass.getMethod(Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Class;)Ljava/lang/reflect/Method; in /data/app/~~x5jMNqx-TxiFPoMGtRaQGA==/com.flairtime.Flare-r-QNkCPaVrUPHTLeSKMkpA==/base.apk!classes2.dex
2023-07-14 21:20:55.640 16914-16914 AndroidRuntime          com.flairtime.Flare                  E  FATAL EXCEPTION: main
                                                                                                    Process: com.flairtime.Flare, PID: 16914
                                                                                                    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/~~x5jMNqx-TxiFPoMGtRaQGA==/com.flairtime.Flare-r-QNkCPaVrUPHTLeSKMkpA==/base.apk!/lib/arm64-v8a/libnrb.so"
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1661)
                                                                                                    	at org.chickenhook.restrictionbypass.NativeReflectionBypass.<clinit>(SourceFile:3)
                                                                                                    	at org.chickenhook.restrictionbypass.a.a(SourceFile:7)
                                                                                                    	at org.chickenhook.restrictionbypass.a.b(SourceFile:12)
                                                                                                    	at org.chickenhook.restrictionbypass.BypassProvider.attachInfo(SourceFile:4)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7474)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6985)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6756)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Goooler** [comment]
You need to add rules from #9 into your proguard-rules.pro
